# Generated by Django 6.0.3 on 2026-05-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm2100', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfm2100device',
            name='datasheet',
            field=models.FileField(blank=True, help_text='Datasheet PDF', null=True, upload_to='pfm2100/datasheets/'),
        ),
        migrations.AddField(
            model_name='pfm2100device',
            name='datasheet_url',
            field=models.URLField(blank=True, help_text='External datasheet URL (optional)'),
        ),
        migrations.AddField(
            model_name='pfm2100device',
            name='image',
            field=models.ImageField(blank=True, help_text='Device photo (JPG, PNG)', null=True, upload_to='pfm2100/devices/'),
        ),
    ]
