# Generated by Django 6.0.3 on 2026-05-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('supply_voltage_min', models.FloatField()),
                ('supply_voltage_max', models.FloatField()),
                ('safety_level', models.CharField(max_length=20)),
                ('max_current_a', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('switch', 'Switch / Limit Switch'), ('valve', 'Hydraulic Valve'), ('indicator', 'Indicator / Horn / Light'), ('relay', 'Relay'), ('fuse', 'Fuse'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cable', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('connector_type', models.CharField(max_length=50)),
                ('primary_role', models.TextField()),
                ('control_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='pal40.controlsystem')),
            ],
        ),
        migrations.AddField(
            model_name='controlsystem',
            name='crane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_systems', to='pal40.crane'),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('function', models.CharField(max_length=200)),
                ('signal_type', models.CharField(choices=[('DI', 'Digital Input'), ('DO', 'Digital Output'), ('AI', 'Analog Input'), ('AO', 'Analog Output'), ('CAN', 'CAN Bus'), ('PWR', 'Power Supply'), ('GND', 'Ground')], max_length=5)),
                ('direction', models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output'), ('BIDI', 'Bidirectional'), ('REF', 'Reference / Return')], max_length=5)),
                ('cable', models.CharField(blank=True, max_length=20)),
                ('wire_color', models.CharField(blank=True, max_length=30)),
                ('terminal', models.CharField(blank=True, max_length=50)),
                ('safety_related', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pal40.connector')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='pal40.device')),
            ],
            options={
                'ordering': ['connector', 'pin_number'],
                'unique_together': {('connector', 'pin_number')},
            },
        ),
        migrations.CreateModel(
            name='SafetyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('safety_level', models.CharField(choices=[('PL_c', 'PL c (IEC 13849)'), ('PL_d', 'PL d (IEC 13849)'), ('SIL_1', 'SIL 1'), ('SIL_2', 'SIL 2')], max_length=10)),
                ('description', models.TextField()),
                ('reaction_time_ms', models.IntegerField(blank=True, null=True)),
                ('pins', models.ManyToManyField(related_name='safety_functions', to='pal40.pin')),
            ],
        ),
        migrations.CreateModel(
            name='SignalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pins', models.ManyToManyField(related_name='signal_groups', to='pal40.pin')),
            ],
        ),
        migrations.CreateModel(
            name='TroubleshootingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=200)),
                ('likely_cause', models.CharField(max_length=200)),
                ('diagnostic_procedure', models.TextField()),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshooting', to='pal40.pin')),
            ],
        ),
    ]
