# Generated by Django 6.0.3 on 2026-05-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PFM1200Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('type_function', models.TextField()),
                ('signal_form', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('classification_notes', models.TextField(blank=True)),
                ('connector_type', models.CharField(blank=True, max_length=20)),
                ('connector_part_number', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Device photo (JPG, PNG)', null=True, upload_to='pfm1200/devices/')),
                ('datasheet', models.FileField(blank=True, help_text='Datasheet PDF', null=True, upload_to='pfm1200/datasheets/')),
                ('datasheet_url', models.URLField(blank=True, help_text='External datasheet URL (optional)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PFM1200Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_id', models.CharField(max_length=20)),
                ('cable_part_number', models.CharField(blank=True, max_length=50)),
                ('connection_details', models.CharField(blank=True, max_length=200)),
                ('junction_box_ref', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='pfm1200.pfm1200device')),
            ],
        ),
        migrations.CreateModel(
            name='PFM1200WireTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('wire_color', models.CharField(max_length=30)),
                ('device_pin', models.CharField(blank=True, max_length=30)),
                ('terminal_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wires', to='pfm1200.pfm1200cable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
