# Generated by Django 6.0.3 on 2026-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm1200', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfm1200device',
            name='device_ref',
            field=models.CharField(blank=True, help_text='Device reference ID (e.g. U205, H113, Y0)', max_length=20),
        ),
    ]
