# Generated by Django 6.0.3 on 2026-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm1200', '0002_pfm1200device_device_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfm1200cable',
            name='length_mm',
            field=models.PositiveIntegerField(default=0, help_text='Total cable length in mm (0 = not specified in drawing)'),
        ),
    ]
